// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetGame.Domain.DataConnection;

namespace PetGame.Migrations
{
    [DbContext(typeof(PetGameDbContext))]
    partial class PetGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetGame.Domain.Entity.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UserPetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserPetId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("PetGame.Domain.Entity.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HappinessRatio")
                        .HasColumnType("int");

                    b.Property<int>("HungerRatio")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HappinessRatio = 2,
                            HungerRatio = 3,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            HappinessRatio = 3,
                            HungerRatio = 2,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            HappinessRatio = 1,
                            HungerRatio = 1,
                            Name = "Bird"
                        });
                });

            modelBuilder.Entity("PetGame.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetGame.Domain.Entity.UserPet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Happiness")
                        .HasColumnType("int");

                    b.Property<int>("Hunger")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PetId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPets");
                });

            modelBuilder.Entity("PetGame.Domain.Entity.Action", b =>
                {
                    b.HasOne("PetGame.Domain.Entity.UserPet", "UserPet")
                        .WithMany("Actions")
                        .HasForeignKey("UserPetId");
                });

            modelBuilder.Entity("PetGame.Domain.Entity.UserPet", b =>
                {
                    b.HasOne("PetGame.Domain.Entity.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");

                    b.HasOne("PetGame.Domain.Entity.User", "User")
                        .WithMany("UserPets")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
